# Generated by Django 5.1.7 on 2025-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_remove_carbonemission_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemission',
            name='_meta_data',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
