# Generated by Django 5.1.7 on 2025-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_alter_carbonemission_options_alter_constants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constants',
            name='anthracite_ch4',
        ),
        migrations.RemoveField(
            model_name='constants',
            name='bituminous_c_ch4',
        ),
        migrations.RemoveField(
            model_name='constants',
            name='bituminous_nc_ch4',
        ),
        migrations.RemoveField(
            model_name='constants',
            name='lignite_ch4',
        ),
        migrations.RemoveField(
            model_name='constants',
            name='subbituminous_ch4',
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='land_disturbance',
            field=models.FloatField(default=0, help_text='Land area disturbed in hectares'),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='sequestration',
            field=models.FloatField(default=0, help_text='Land area reforested in hectar acres'),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='total_ch4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='waste',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='constants',
            name='csl',
            field=models.FloatField(default=0.5),
        ),
    ]
