# Generated by Django 5.1.7 on 2025-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_carbonemission__meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonemission',
            name='id',
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='project_name',
            field=models.CharField(default='Unnamed Project', max_length=200, primary_key=True, serialize=False),
        ),
    ]
