# Generated by Django 5.1.5 on 2025-03-18 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Constants', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine_type', models.CharField(choices=[('open-cast', 'Open Cast Coal Mine'), ('underground', 'Underground Coal Mine')], default='open-cast', max_length=20)),
                ('anthracite_cf', models.FloatField(default=26.8)),
                ('bituminous_nc_cf', models.FloatField(default=25.8)),
                ('bituminous_c_cf', models.FloatField(default=25.8)),
                ('lignite_cf', models.FloatField(default=14.1)),
                ('subbituminous_cf', models.FloatField(default=18.9)),
                ('conv_fact', models.FloatField(default=4.1868)),
                ('exclusion_fact', models.FloatField(default=12.0)),
                ('anthracite_cc', models.FloatField(default=26.8)),
                ('bituminous_nc_cc', models.FloatField(default=25.8)),
                ('bituminous_c_cc', models.FloatField(default=25.8)),
                ('lignite_cc', models.FloatField(default=27.6)),
                ('subbituminous_cc', models.FloatField(default=26.2)),
                ('anthracite_cof', models.FloatField(default=0.98)),
                ('bituminous_nc_cof', models.FloatField(default=0.98)),
                ('bituminous_c_cof', models.FloatField(default=0.98)),
                ('lignite_cof', models.FloatField(default=0.98)),
                ('subbituminous_cof', models.FloatField(default=0.98)),
                ('anthracite_ch4', models.FloatField(default=0.3)),
                ('bituminous_nc_ch4', models.FloatField(default=0.3)),
                ('bituminous_c_ch4', models.FloatField(default=0.3)),
                ('lignite_ch4', models.FloatField(default=0.1)),
                ('subbituminous_ch4', models.FloatField(default=0.2)),
                ('diesel_ef', models.FloatField(default=2.68)),
                ('petrol_ef', models.FloatField(default=2.31)),
                ('grid_emission_factor', models.FloatField(default=0.82)),
                ('carbon_sequesteration_rate', models.FloatField(default=10.0)),
                ('overburden_ef', models.FloatField(default=0.5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Explosive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explosive_type', models.CharField(max_length=100)),
                ('emission_factor', models.FloatField(help_text='Emission factor in kg CO₂/kg')),
                ('constants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explosives', to='Model.constants')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=100)),
                ('emission_factor', models.FloatField(help_text='Emission factor in kg CO₂/km')),
                ('constants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='Model.constants')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(default='Unnamed Project', max_length=200)),
                ('anthracite', models.FloatField(default=0, help_text='Anthracite production in tonnes')),
                ('bituminous_coking', models.FloatField(default=0, help_text='Bituminous coking production in tonnes')),
                ('bituminous_non_coking', models.FloatField(default=0, help_text='Bituminous non-coking production in tonnes')),
                ('subbituminous', models.FloatField(default=0, help_text='Subbituminous production in tonnes')),
                ('lignite', models.FloatField(default=0, help_text='Lignite production in tonnes')),
                ('diesel_used', models.FloatField(default=0, help_text='Diesel used in liters')),
                ('petrol_used', models.FloatField(default=0, help_text='Petrol used in liters')),
                ('explosives_used', models.FloatField(default=0, help_text='Explosives used in kg')),
                ('electricity_used', models.FloatField(default=0, help_text='Electricity used in MWh')),
                ('overburden_removed', models.FloatField(default=0, help_text='Overburden removed in cubic meters')),
                ('transport_distance', models.FloatField(default=0, help_text='Transport distance in km')),
                ('total_emissions', models.FloatField(default=0, help_text='Total emissions in tonnes CO₂e')),
                ('emissions_per_tonne', models.FloatField(default=0, help_text='Emissions per tonne of coal in tonnes CO₂e/tonne')),
                ('coal_emissions', models.FloatField(default=0)),
                ('diesel_emissions', models.FloatField(default=0)),
                ('petrol_emissions', models.FloatField(default=0)),
                ('explosive_emissions', models.FloatField(default=0)),
                ('electricity_emissions', models.FloatField(default=0)),
                ('transport_emissions', models.FloatField(default=0)),
                ('methane_emissions', models.FloatField(default=0)),
                ('overburden_emissions', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('constants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.constants')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.transport')),
            ],
        ),
    ]
