# Generated by Django 5.1.7 on 2025-03-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbonemission',
            options={'verbose_name': 'Carbon Emission', 'verbose_name_plural': 'Carbon Emissions'},
        ),
        migrations.AlterModelOptions(
            name='constants',
            options={'verbose_name': 'Constants', 'verbose_name_plural': 'Constants'},
        ),
    ]
