# Generated by Django 5.1.7 on 2025-03-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_carbonemission_is_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonemission',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='Net_Carbon_Footprint',
            field=models.FloatField(default=0),
        ),
    ]
