# Generated by Django 5.1.7 on 2025-04-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_remove_carbonemission_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemission',
            name='transport_weights',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
