# Generated by Django 5.1.7 on 2025-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_add_transport_weights_to_carbonemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='methane_emission_factor',
            field=models.FloatField(default=0.00067, help_text='Methane emission factor (conversion to CO₂e)'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='anthracite_cc',
            field=models.FloatField(default=98.3),
        ),
        migrations.AlterField(
            model_name='constants',
            name='anthracite_cf',
            field=models.FloatField(default=26.7),
        ),
        migrations.AlterField(
            model_name='constants',
            name='bituminous_c_cc',
            field=models.FloatField(default=94.6),
        ),
        migrations.AlterField(
            model_name='constants',
            name='bituminous_nc_cc',
            field=models.FloatField(default=94.6),
        ),
        migrations.AlterField(
            model_name='constants',
            name='carbon_sequesteration_rate',
            field=models.FloatField(default=3.5),
        ),
        migrations.AlterField(
            model_name='constants',
            name='csl',
            field=models.FloatField(default=750),
        ),
        migrations.AlterField(
            model_name='constants',
            name='diesel_ef',
            field=models.FloatField(default=0.00268),
        ),
        migrations.AlterField(
            model_name='constants',
            name='exclusion_fact',
            field=models.FloatField(default=0.017),
        ),
        migrations.AlterField(
            model_name='constants',
            name='grid_emission_factor',
            field=models.FloatField(default=0.708),
        ),
        migrations.AlterField(
            model_name='constants',
            name='lignite_cc',
            field=models.FloatField(default=101.0),
        ),
        migrations.AlterField(
            model_name='constants',
            name='lignite_cf',
            field=models.FloatField(default=11.9),
        ),
        migrations.AlterField(
            model_name='constants',
            name='overburden_ef',
            field=models.FloatField(default=0.00025),
        ),
        migrations.AlterField(
            model_name='constants',
            name='petrol_ef',
            field=models.FloatField(default=0.00231),
        ),
        migrations.AlterField(
            model_name='constants',
            name='subbituminous_cc',
            field=models.FloatField(default=96.1),
        ),
        migrations.AlterField(
            model_name='constants',
            name='waste_ef',
            field=models.FloatField(default=0.005),
        ),
    ]
